version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  api:
    container_name: api-container
    image: node:12
    user: 1000:1000
    working_dir: /home/app
    restart: always
    command: bash -c "yarn debug"
    volumes:
      - ./:/home/app
      - ~/.gitconfig-docker:/etc/gitconfig
    ports:
      - "5050:5050"
      - "9222:9222"
    links:
      - mongo